- hosts: linux
  vars:
    training:
      topic: ansible
      trainer: sathish
      lab: aws
    test:
      topic: hi
  tasks:
  - name: print dict variable
    debug: msg="{{training.topic}} {{training['trainer']}} {{ training.lab}} {{test.topic}}"
