- hosts: linux
  ignore_errors: yes
  tasks:
  - name: print output
    bash: echo $HOSTNAME
    register: cmdoutput
  - debug: msg="standard output={{cmdoutput.stdout}}"
  - debug: msg="standart error={{cmdoutput.stderr}}"
